import type { ThemePreset } from './types';

/** The richer looks the built-in templates ship with: gradients, shadows, and set fonts. */
export const designedPresets: ThemePreset[] = [
  {
    id: 'nightshift',
    name: 'Nightshift',
    theme: {
      pageBg: '#0f172a',
      cardBg: '#111827',
      cardBorder: '#1f2937',
      accentColor: '#38bdf8',
      labelColor: '#e2e8f0',
      inputBg: '#1a2333',
      inputBorder: '#2b3648',
      inputTextColor: '#f8fafc',
      textMode: 'light',
      cardRadius: 16,
      cardShadow: 'lg',
      fontFamily: 'inter',
      pageBackground: {
        gradient: 'linear-gradient(160deg, #0f172a 0%, #0e7490 100%)',
        overlay: '#000000',
        overlayOpacity: 25,
      },
    },
  },
  {
    id: 'violetdusk',
    name: 'Violet Dusk',
    theme: {
      pageBg: '#1e1b4b',
      cardBg: '#ffffff',
      cardBorder: '#e9d5ff',
      accentColor: '#7c3aed',
      labelColor: '#1e1b4b',
      inputBg: '#faf8ff',
      inputBorder: '#ddd6fe',
      inputTextColor: '#1e1b4b',
      textMode: 'dark',
      cardRadius: 18,
      cardShadow: 'xl',
      fontFamily: 'inter',
      pageBackground: { gradient: 'linear-gradient(135deg, #1e3a8a 0%, #7e22ce 100%)' },
    },
  },
  {
    id: 'glasspane',
    name: 'Glass',
    theme: {
      pageBg: '#0f172a',
      cardBg: '#ffffff',
      cardBorder: '#ffffff',
      accentColor: '#6366f1',
      labelColor: '#0f172a',
      inputBg: '#ffffff',
      inputBorder: '#c7d2fe',
      inputTextColor: '#0f172a',
      textMode: 'dark',
      cardRadius: 20,
      cardShadow: 'xl',
      cardOpacity: 85,
      cardBlur: 14,
      fontFamily: 'inter',
      pageBackground: { gradient: 'linear-gradient(120deg, #a7f3d0 0%, #93c5fd 50%, #c4b5fd 100%)' },
    },
  },
  {
    id: 'deepwater',
    name: 'Deep Water',
    theme: {
      pageBg: '#0b0f14',
      cardBg: '#12171f',
      cardBorder: '#1e2733',
      accentColor: '#22d3ee',
      labelColor: '#e2e8f0',
      inputBg: '#182029',
      inputBorder: '#26313d',
      inputTextColor: '#f1f5f9',
      textMode: 'light',
      cardRadius: 14,
      cardShadow: 'lg',
      fontFamily: 'inter',
      pageBackground: {
        gradient: 'radial-gradient(circle at 30% 20%, #38bdf8 0%, #0f172a 70%)',
        overlay: '#000000',
        overlayOpacity: 40,
      },
    },
  },
  {
    id: 'apothecary',
    name: 'Apothecary',
    theme: {
      pageBg: '#ecfdf5',
      cardBg: '#ffffff',
      cardBorder: '#bbf7d0',
      accentColor: '#0d9488',
      labelColor: '#134e4a',
      inputBg: '#f7fefb',
      inputBorder: '#a7f3d0',
      inputTextColor: '#134e4a',
      textMode: 'dark',
      cardRadius: 16,
      cardShadow: 'md',
      fontFamily: 'rounded',
      pageBackground: {
        gradient: 'linear-gradient(135deg, #10b981 0%, #06b6d4 100%)',
        overlay: '#ffffff',
        overlayOpacity: 55,
      },
    },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    theme: {
      pageBg: '#0d1117',
      cardBg: '#161b22',
      cardBorder: '#30363d',
      accentColor: '#f78166',
      labelColor: '#c9d1d9',
      inputBg: '#0d1117',
      inputBorder: '#30363d',
      inputTextColor: '#e6edf3',
      textMode: 'light',
      cardRadius: 8,
      cardShadow: 'sm',
      fontFamily: 'mono',
    },
  },
  {
    id: 'apricot',
    name: 'Apricot',
    theme: {
      pageBg: '#fef3c7',
      cardBg: '#ffffff',
      cardBorder: '#fde68a',
      accentColor: '#d97706',
      labelColor: '#451a03',
      inputBg: '#fffbeb',
      inputBorder: '#fcd34d',
      inputTextColor: '#451a03',
      textMode: 'dark',
      cardRadius: 20,
      cardShadow: 'lg',
      fontFamily: 'rounded',
      pageBackground: { gradient: 'linear-gradient(135deg, #fde68a 0%, #fca5a5 100%)' },
    },
  },
  {
    id: 'gazette',
    name: 'Gazette',
    theme: {
      pageBg: '#7f1d1d',
      cardBg: '#ffffff',
      cardBorder: '#fecaca',
      accentColor: '#dc2626',
      labelColor: '#450a0a',
      inputBg: '#fffafa',
      inputBorder: '#fecaca',
      inputTextColor: '#450a0a',
      textMode: 'dark',
      cardRadius: 16,
      cardShadow: 'xl',
      fontFamily: 'serif',
      pageBackground: {
        gradient: 'linear-gradient(135deg, #7f1d1d 0%, #b45309 100%)',
        overlay: '#000000',
        overlayOpacity: 20,
      },
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    theme: {
      pageBg: '#111827',
      cardBg: '#f9fafb',
      cardBorder: '#e5e7eb',
      accentColor: '#111827',
      labelColor: '#111827',
      inputBg: '#ffffff',
      inputBorder: '#d1d5db',
      inputTextColor: '#111827',
      textMode: 'dark',
      cardRadius: 10,
      cardShadow: 'xl',
      fontFamily: 'inter',
      pageBackground: { gradient: 'linear-gradient(180deg, #1f2937 0%, #111827 100%)' },
    },
  },
  {
    id: 'cottoncandy',
    name: 'Cotton Candy',
    theme: {
      pageBg: '#fdf2f8',
      cardBg: '#ffffff',
      cardBorder: '#fbcfe8',
      accentColor: '#db2777',
      labelColor: '#500724',
      inputBg: '#fffafc',
      inputBorder: '#f9cee5',
      inputTextColor: '#3f0f26',
      textMode: 'dark',
      cardRadius: 22,
      cardShadow: 'lg',
      fontFamily: 'rounded',
      pageBackground: { gradient: 'linear-gradient(135deg, #f9a8d4 0%, #a5b4fc 100%)' },
    },
  },
];
