import type { ThemePreset } from './types';

/** Flat, single-colour palettes — the safe defaults. */
export const solidPresets: ThemePreset[] = [
  {
    id: 'classic',
    name: 'Classic',
    theme: {
      pageBg: '#f1f3f5',
      cardBg: '#ffffff',
      cardBorder: '#e9ecef',
      accentColor: '#4c6ef5',
      labelColor: '#212529',
      inputBg: '#ffffff',
      inputBorder: '#ced4da',
      inputTextColor: '#212529',
      textMode: 'dark',
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    theme: {
      pageBg: '#ffffff',
      cardBg: '#ffffff',
      cardBorder: '#e5e7eb',
      accentColor: '#2563eb',
      labelColor: '#111827',
      inputBg: '#ffffff',
      inputBorder: '#d1d5db',
      inputTextColor: '#111827',
      textMode: 'dark',
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    theme: {
      pageBg: '#fafafa',
      cardBg: '#ffffff',
      cardBorder: '#e5e5e5',
      accentColor: '#171717',
      labelColor: '#171717',
      inputBg: '#fafafa',
      inputBorder: '#d4d4d4',
      inputTextColor: '#171717',
      textMode: 'dark',
    },
  },
  {
    id: 'ink',
    name: 'Ink',
    theme: {
      pageBg: '#111827',
      cardBg: '#ffffff',
      cardBorder: '#ffffff',
      accentColor: '#111827',
      labelColor: '#111827',
      inputBg: '#f9fafb',
      inputBorder: '#d1d5db',
      inputTextColor: '#111827',
      textMode: 'dark',
    },
  },
  {
    id: 'steel',
    name: 'Steel',
    theme: {
      pageBg: '#e2e8f0',
      cardBg: '#ffffff',
      cardBorder: '#cbd5e1',
      accentColor: '#475569',
      labelColor: '#0f172a',
      inputBg: '#f8fafc',
      inputBorder: '#cbd5e1',
      inputTextColor: '#0f172a',
      textMode: 'dark',
    },
  },
  {
    id: 'sand',
    name: 'Sand',
    theme: {
      pageBg: '#efe7db',
      cardBg: '#fdfaf5',
      cardBorder: '#e0d5c3',
      accentColor: '#a16207',
      labelColor: '#3f2d13',
      inputBg: '#ffffff',
      inputBorder: '#ded2be',
      inputTextColor: '#3f2d13',
      textMode: 'dark',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    theme: {
      pageBg: '#0b0c0f',
      cardBg: '#15171c',
      cardBorder: '#25272e',
      accentColor: '#5c7cfa',
      labelColor: '#e9ecef',
      inputBg: '#1c1e25',
      inputBorder: '#2f323b',
      inputTextColor: '#f1f3f5',
      textMode: 'light',
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    theme: {
      pageBg: '#1c1c1e',
      cardBg: '#2c2c2e',
      cardBorder: '#3a3a3c',
      accentColor: '#0a84ff',
      labelColor: '#f2f2f7',
      inputBg: '#3a3a3c',
      inputBorder: '#48484a',
      inputTextColor: '#ffffff',
      textMode: 'light',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    theme: {
      pageBg: '#1e293b',
      cardBg: '#293548',
      cardBorder: '#3a4759',
      accentColor: '#38bdf8',
      labelColor: '#e2e8f0',
      inputBg: '#334155',
      inputBorder: '#475569',
      inputTextColor: '#f1f5f9',
      textMode: 'light',
    },
  },
  {
    id: 'coffee',
    name: 'Coffee',
    theme: {
      pageBg: '#2b1d16',
      cardBg: '#3b2a20',
      cardBorder: '#543d2f',
      accentColor: '#d9a066',
      labelColor: '#f3e6da',
      inputBg: '#473327',
      inputBorder: '#63483a',
      inputTextColor: '#f8f1ea',
      textMode: 'light',
    },
  },
];
