import type { ThemePreset } from './types';

export const studioPresets: ThemePreset[] = [
  {
    id: 'studio',
    name: 'Studio',
    theme: {
      pageBg: '#f5f5f7',
      cardBg: '#ffffff',
      cardBorder: '#e8e8ed',
      accentColor: '#0071e3',
      labelColor: '#1d1d1f',
      inputBg: '#f5f5f7',
      inputBorder: '#f5f5f7',
      inputTextColor: '#1d1d1f',
      textMode: 'dark',
      cardRadius: 28,
      cardShadow: 'sm',
      fontFamily: 'inter',
      fieldStyle: 'filled',
      fieldRadius: 12,
      buttonShape: 'pill',
      density: 'spacious',
      titleSize: 'lg',
      cardWidth: 'narrow',
    },
  },
  {
    id: 'studio-dark',
    name: 'Studio Dark',
    theme: {
      pageBg: '#000000',
      cardBg: '#1c1c1e',
      cardBorder: '#2c2c2e',
      accentColor: '#0a84ff',
      labelColor: '#f5f5f7',
      inputBg: '#2c2c2e',
      inputBorder: '#2c2c2e',
      inputTextColor: '#f5f5f7',
      textMode: 'light',
      cardRadius: 28,
      cardShadow: 'none',
      fontFamily: 'inter',
      fieldStyle: 'filled',
      fieldRadius: 12,
      buttonShape: 'pill',
      density: 'spacious',
      titleSize: 'lg',
      cardWidth: 'narrow',
    },
  },
  {
    id: 'editorial',
    name: 'Editorial',
    theme: {
      pageBg: '#faf9f6',
      cardBg: '#faf9f6',
      cardBorder: '#faf9f6',
      accentColor: '#111111',
      labelColor: '#111111',
      inputBg: '#faf9f6',
      inputBorder: '#cfccc4',
      inputTextColor: '#111111',
      textMode: 'dark',
      fontFamily: 'fraunces',
      surface: 'flat',
      fieldStyle: 'underline',
      fieldRadius: 0,
      buttonShape: 'pill',
      density: 'spacious',
      titleSize: 'xl',
      cardWidth: 'narrow',
    },
  },
  {
    id: 'aurora-glass',
    name: 'Aurora Glass',
    theme: {
      pageBg: '#05060a',
      cardBg: '#111827',
      cardBorder: '#2a3245',
      accentColor: '#a78bfa',
      labelColor: '#e5e7eb',
      inputBg: '#0b1020',
      inputBorder: '#2a3245',
      inputTextColor: '#f9fafb',
      textMode: 'light',
      cardRadius: 24,
      cardShadow: 'xl',
      cardOpacity: 65,
      cardBlur: 24,
      fontFamily: 'jakarta',
      fieldStyle: 'outline',
      fieldRadius: 12,
      buttonShape: 'pill',
      density: 'comfortable',
      titleSize: 'lg',
      pageBackground: {
        gradient:
          'radial-gradient(circle at 18% 12%, #5b21b6 0%, transparent 42%), radial-gradient(circle at 85% 88%, #0e7490 0%, transparent 40%)',
      },
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    theme: {
      pageBg: '#08090a',
      cardBg: '#0f1011',
      cardBorder: '#1f2023',
      accentColor: '#5e6ad2',
      labelColor: '#e6e6e6',
      inputBg: '#151618',
      inputBorder: '#26272b',
      inputTextColor: '#f7f8f8',
      textMode: 'light',
      cardRadius: 14,
      cardShadow: 'lg',
      fontFamily: 'inter',
      fieldStyle: 'outline',
      fieldRadius: 8,
      buttonShape: 'match',
      density: 'compact',
      titleSize: 'md',
    },
  },
  {
    id: 'sand',
    name: 'Sand',
    theme: {
      pageBg: '#efe9df',
      cardBg: '#fffdf9',
      cardBorder: '#e6ded1',
      accentColor: '#1f1d1a',
      labelColor: '#2b2722',
      inputBg: '#f6f0e6',
      inputBorder: '#f6f0e6',
      inputTextColor: '#2b2722',
      textMode: 'dark',
      cardRadius: 24,
      cardShadow: 'sm',
      fontFamily: 'dmSans',
      fieldStyle: 'filled',
      fieldRadius: 10,
      buttonShape: 'pill',
      density: 'spacious',
      titleSize: 'lg',
      cardWidth: 'narrow',
    },
  },
  {
    id: 'indigo-pro',
    name: 'Indigo',
    theme: {
      pageBg: '#f6f8fc',
      cardBg: '#ffffff',
      cardBorder: '#e5e7f0',
      accentColor: '#4f46e5',
      labelColor: '#111827',
      inputBg: '#ffffff',
      inputBorder: '#d9dce8',
      inputTextColor: '#111827',
      textMode: 'dark',
      cardRadius: 20,
      cardShadow: 'md',
      fontFamily: 'manrope',
      fieldStyle: 'outline',
      fieldRadius: 10,
      buttonShape: 'match',
      density: 'comfortable',
      titleSize: 'lg',
      pageBackground: { gradient: 'linear-gradient(180deg, #e0e7ff 0%, #f6f8fc 55%)' },
    },
  },
  {
    id: 'volt',
    name: 'Volt',
    theme: {
      pageBg: '#d9f99d',
      cardBg: '#0a0a0a',
      cardBorder: '#0a0a0a',
      accentColor: '#d9f99d',
      labelColor: '#fafafa',
      inputBg: '#171717',
      inputBorder: '#2a2a2a',
      inputTextColor: '#fafafa',
      textMode: 'light',
      cardRadius: 6,
      cardShadow: 'none',
      fontFamily: 'grotesk',
      fieldStyle: 'outline',
      fieldRadius: 4,
      buttonShape: 'match',
      density: 'comfortable',
      titleSize: 'xl',
    },
  },
  {
    id: 'blush',
    name: 'Blush',
    theme: {
      pageBg: '#fff1f2',
      cardBg: '#ffffff',
      cardBorder: '#ffe4e6',
      accentColor: '#e11d48',
      labelColor: '#3f0d17',
      inputBg: '#fff7f8',
      inputBorder: '#fecdd3',
      inputTextColor: '#3f0d17',
      textMode: 'dark',
      cardRadius: 24,
      cardShadow: 'md',
      fontFamily: 'jakarta',
      fieldStyle: 'outline',
      fieldRadius: 14,
      buttonShape: 'pill',
      buttonStyle: 'solid',
      density: 'comfortable',
      titleSize: 'lg',
      cardWidth: 'narrow',
      pageBackground: { gradient: 'linear-gradient(160deg, #ffe4e6 0%, #fff7ed 100%)' },
    },
  },
];
