import type { ThemePreset } from './types';

/** A coloured page behind a light card. */
export const tintedPresets: ThemePreset[] = [
  {
    id: 'sky',
    name: 'Sky',
    theme: {
      pageBg: '#dbeafe',
      cardBg: '#ffffff',
      cardBorder: '#bfdbfe',
      accentColor: '#2563eb',
      labelColor: '#1e293b',
      inputBg: '#f8fafc',
      inputBorder: '#cbd5e1',
      inputTextColor: '#0f172a',
      textMode: 'dark',
    },
  },
  {
    id: 'blush',
    name: 'Blush',
    theme: {
      pageBg: '#fce7f3',
      cardBg: '#ffffff',
      cardBorder: '#f9cee5',
      accentColor: '#db2777',
      labelColor: '#500724',
      inputBg: '#fffafc',
      inputBorder: '#f5cddf',
      inputTextColor: '#3f0f26',
      textMode: 'dark',
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    theme: {
      pageBg: '#fef3c7',
      cardBg: '#ffffff',
      cardBorder: '#fde68a',
      accentColor: '#d97706',
      labelColor: '#451a03',
      inputBg: '#fffbeb',
      inputBorder: '#fcd34d',
      inputTextColor: '#451a03',
      textMode: 'dark',
    },
  },
  {
    id: 'grape',
    name: 'Grape',
    theme: {
      pageBg: '#ede9fe',
      cardBg: '#ffffff',
      cardBorder: '#ddd6fe',
      accentColor: '#7c3aed',
      labelColor: '#2e1065',
      inputBg: '#faf8ff',
      inputBorder: '#d8ccff',
      inputTextColor: '#2e1065',
      textMode: 'dark',
    },
  },
  {
    id: 'teal',
    name: 'Teal',
    theme: {
      pageBg: '#ccfbf1',
      cardBg: '#ffffff',
      cardBorder: '#99f6e4',
      accentColor: '#0d9488',
      labelColor: '#134e4a',
      inputBg: '#f0fdfa',
      inputBorder: '#99f6e4',
      inputTextColor: '#134e4a',
      textMode: 'dark',
    },
  },
  {
    id: 'crimson',
    name: 'Crimson',
    theme: {
      pageBg: '#fee2e2',
      cardBg: '#ffffff',
      cardBorder: '#fecaca',
      accentColor: '#dc2626',
      labelColor: '#450a0a',
      inputBg: '#fffafa',
      inputBorder: '#fecaca',
      inputTextColor: '#450a0a',
      textMode: 'dark',
    },
  },
  {
    id: 'mint',
    name: 'Mint',
    theme: {
      pageBg: '#dcfce7',
      cardBg: '#ffffff',
      cardBorder: '#bbf7d0',
      accentColor: '#16a34a',
      labelColor: '#14532d',
      inputBg: '#f7fef9',
      inputBorder: '#bbf7d0',
      inputTextColor: '#14532d',
      textMode: 'dark',
    },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    theme: {
      pageBg: '#f3d9d3',
      cardBg: '#ffffff',
      cardBorder: '#e8c4bb',
      accentColor: '#b76e79',
      labelColor: '#4a2c2a',
      inputBg: '#fffbfa',
      inputBorder: '#e8c4bb',
      inputTextColor: '#4a2c2a',
      textMode: 'dark',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    theme: {
      pageBg: '#fb923c',
      cardBg: '#ffffff',
      cardBorder: '#fed7aa',
      accentColor: '#ea580c',
      labelColor: '#431407',
      inputBg: '#fffbf7',
      inputBorder: '#fed7aa',
      inputTextColor: '#431407',
      textMode: 'dark',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    theme: {
      pageBg: '#052e23',
      cardBg: '#0b4034',
      cardBorder: '#125a48',
      accentColor: '#10b981',
      labelColor: '#d1fae5',
      inputBg: '#0f4c3d',
      inputBorder: '#166b55',
      inputTextColor: '#ecfdf5',
      textMode: 'light',
    },
  },
  {
    id: 'lagoon',
    name: 'Lagoon',
    theme: {
      pageBg: '#082f49',
      cardBg: '#0c4a6e',
      cardBorder: '#155e83',
      accentColor: '#22d3ee',
      labelColor: '#e0f2fe',
      inputBg: '#0e5a83',
      inputBorder: '#1a6f9c',
      inputTextColor: '#f0f9ff',
      textMode: 'light',
    },
  },
  {
    id: 'plum',
    name: 'Plum',
    theme: {
      pageBg: '#2e1065',
      cardBg: '#3b1d7a',
      cardBorder: '#4c2a95',
      accentColor: '#c084fc',
      labelColor: '#ede9fe',
      inputBg: '#452490',
      inputBorder: '#5b34ad',
      inputTextColor: '#f5f3ff',
      textMode: 'light',
    },
  },
  {
    id: 'lime',
    name: 'Lime',
    theme: {
      pageBg: '#1a2e05',
      cardBg: '#233d08',
      cardBorder: '#365314',
      accentColor: '#a3e635',
      labelColor: '#ecfccb',
      inputBg: '#2b4a0c',
      inputBorder: '#3f6212',
      inputTextColor: '#f7fee7',
      textMode: 'light',
    },
  },
];
