import type { FormTemplate } from '../types';
import { field, pageBreak, row } from '../types';
import { email, fullName, look, longText, multiPills, phone, pick, pills } from '../proKit';

export const proBusinessTemplates: FormTemplate[] = [
  {
    id: 'pro-quote-request',
    name: 'Quote request',
    description: 'Scope, budget and timeline for service businesses quoting new work.',
    category: 'Business',
    keywords: ['quote', 'estimate', 'proposal', 'pricing', 'services'],
    title: 'Request a quote',
    formDescription: 'Share the essentials and we will send a detailed estimate within two business days.',
    submitLabel: 'Get my quote',
    fields: [
      fullName(),
      row([email('Work email')], [field('text', { label: 'Company', placeholder: 'Acme Inc.' })]),
      multiPills('Services needed', ['Strategy', 'Design', 'Development', 'Marketing', 'Support'], { required: true }),
      longText('Project details', 'What you need, who it is for, and any constraints.', true),
      row(
        [pick('Budget', ['Under $5k', '$5k – $15k', '$15k – $50k', '$50k+'], { required: true })],
        [pick('Timeline', ['ASAP', 'Within a month', '1–3 months', 'Flexible'])]
      ),
      field('file', { label: 'Attachments', helpText: 'Briefs, specs or references. Optional.' }),
    ],
    theme: look('indigo-pro', { accentColor: '#0f766e', pageBackground: { gradient: 'linear-gradient(180deg, #ccfbf1 0%, #f6f8fc 55%)' } }),
  },
  {
    id: 'pro-partner-application',
    name: 'Partner program',
    description: 'A two-step application for agencies and resellers joining a partner program.',
    category: 'Business',
    keywords: ['partner', 'reseller', 'agency', 'affiliate', 'channel'],
    title: 'Become a partner',
    formDescription: 'Grow with us. Partners get revenue share, early access and a dedicated manager.',
    submitLabel: 'Apply now',
    stepIndicator: 'progress',
    showStepHeadings: true,
    steps: [
      { title: 'Your company', description: 'Tell us who you are.' },
      { title: 'Fit', description: 'How we would work together.' },
    ],
    fields: [
      fullName('Contact name'),
      row([email('Work email')], [phone()]),
      row(
        [field('text', { label: 'Company', required: true, placeholder: 'Northwind Agency' })],
        [field('website', { label: 'Website', required: true, placeholder: 'northwind.co' })]
      ),
      row([field('country', { label: 'Headquarters' })], [pick('Team size', ['1–10', '11–50', '51–200', '200+'])]),
      pageBreak(),
      pills('Partner type', ['Agency', 'Reseller', 'Technology', 'Referral'], { required: true }),
      pick('Clients served per year', ['Under 10', '10–50', '50–200', '200+']),
      longText('Why partner with us?', 'Your clients, your expertise, and where we fit.', true),
    ],
    theme: look('graphite', { accentColor: '#22c55e' }),
  },
  {
    id: 'pro-rfp-intake',
    name: 'RFP intake',
    description: 'A structured request-for-proposal form with requirements and deadlines.',
    category: 'Business',
    keywords: ['rfp', 'procurement', 'vendor', 'tender', 'proposal'],
    title: 'Request for proposal',
    formDescription: 'Outline your requirements and we will respond with a formal proposal.',
    submitLabel: 'Submit RFP',
    fields: [
      row([field('text', { label: 'Organisation', required: true, placeholder: 'City of Springfield' })], [field('text', { label: 'Project name', required: true, placeholder: 'Website redesign' })]),
      fullName('Point of contact'),
      row([email()], [phone()]),
      longText('Scope of work', 'Deliverables, requirements, and success criteria.', true),
      row([field('date', { label: 'Proposal due', required: true })], [field('date', { label: 'Expected start' })]),
      field('currency', { label: 'Budget ceiling' }),
      field('file', { label: 'RFP document', helpText: 'PDF or Word.' }),
    ],
    theme: look('editorial', { fontFamily: 'manrope', titleSize: 'lg' }),
  },
  {
    id: 'pro-investor-intro',
    name: 'Investor introduction',
    description: 'A crisp founder pitch form for funds and angel networks.',
    category: 'Business',
    keywords: ['startup', 'investor', 'pitch', 'fundraise', 'vc', 'angel'],
    title: 'Pitch us',
    formDescription: 'We review every submission and reply within ten days.',
    submitLabel: 'Send pitch',
    fields: [
      fullName('Founder name'),
      row([email()], [field('website', { label: 'Company website', required: true, placeholder: 'startup.com' })]),
      field('text', { label: 'One-line description', required: true, placeholder: 'Stripe for logistics in Southeast Asia' }),
      row(
        [pick('Stage', ['Pre-seed', 'Seed', 'Series A', 'Series B+'], { required: true })],
        [pick('Raising', ['Under $500k', '$500k – $2M', '$2M – $10M', '$10M+'])]
      ),
      multiPills('Sector', ['AI', 'Fintech', 'Health', 'Climate', 'Consumer', 'B2B SaaS', 'Other']),
      field('file', { label: 'Pitch deck', required: true, helpText: 'PDF, up to 20 MB.' }),
      longText('Traction', 'Revenue, users, growth rate — whatever tells the story.'),
    ],
    theme: look('aurora-glass', { accentColor: '#38bdf8' }),
  },
  {
    id: 'pro-sales-contact',
    name: 'Contact sales',
    description: 'A focused enterprise sales form that routes by company size.',
    category: 'Business',
    keywords: ['sales', 'enterprise', 'contact', 'pricing', 'lead'],
    title: 'Talk to sales',
    formDescription: 'Custom pricing, security reviews and volume discounts for teams of every size.',
    submitLabel: 'Contact sales',
    fields: [
      fullName(),
      row([email('Work email', true, 'you@company.com')], [phone()]),
      row([field('text', { label: 'Company', required: true, placeholder: 'Acme Inc.' })], [pick('Employees', ['1–49', '50–249', '250–999', '1,000+'], { required: true })]),
      pills('Primary goal', ['Evaluate', 'Migrate', 'Expand', 'Renew']),
      longText('How can we help?', 'Tell us about your use case.'),
      field('decisionBox', { label: 'Keep me updated on product news' }),
    ],
    theme: look('studio', { accentColor: '#111111' }),
  },
  {
    id: 'pro-vendor-onboarding',
    name: 'Vendor onboarding',
    description: 'Collect supplier details, tax info and banking in three tidy steps.',
    category: 'Business',
    keywords: ['vendor', 'supplier', 'procurement', 'onboarding', 'finance'],
    title: 'Supplier onboarding',
    formDescription: 'Required before we can raise purchase orders. Takes about five minutes.',
    submitLabel: 'Submit details',
    stepIndicator: 'stepper',
    showStepHeadings: true,
    steps: [
      { title: 'Company', description: 'Legal entity details.' },
      { title: 'Contact', description: 'Who handles orders and invoices.' },
      { title: 'Finance', description: 'Tax and payment details.' },
    ],
    fields: [
      field('text', { label: 'Legal company name', required: true, placeholder: 'Northwind Supplies Ltd' }),
      row([field('text', { label: 'Registration number', placeholder: '12345678' })], [field('country', { label: 'Country', required: true })]),
      field('address', { label: 'Registered address', required: true }),
      pageBreak(),
      fullName('Account manager'),
      row([email()], [phone('Phone', true)]),
      email('Invoices email', true, 'accounts@supplier.com'),
      pageBreak(),
      field('text', { label: 'Tax / VAT ID', required: true, placeholder: 'GB123456789' }),
      pills('Payment terms', ['Net 15', 'Net 30', 'Net 60']),
      field('file', { label: 'Tax certificate', required: true }),
      field('terms', { label: 'I confirm these details are accurate', required: true }),
    ],
    theme: look('indigo-pro'),
  },
  {
    id: 'pro-media-inquiry',
    name: 'Press inquiry',
    description: 'A newsroom-style form for journalists and media requests.',
    category: 'Business',
    keywords: ['press', 'media', 'journalist', 'pr', 'interview'],
    title: 'Press & media',
    formDescription: 'For interviews, comments and press materials. We respond to media within 24 hours.',
    submitLabel: 'Send request',
    fields: [
      fullName(),
      row([email()], [field('text', { label: 'Publication', required: true, placeholder: 'The Daily Planet' })]),
      pills('Request type', ['Interview', 'Comment', 'Press kit', 'Other'], { required: true }),
      row([field('date', { label: 'Deadline' })], [field('website', { label: 'Link to your work', placeholder: 'dailyplanet.com/you' })]),
      longText('Details', 'Topic, angle and any specific questions.', true),
    ],
    theme: look('editorial'),
  },
  {
    id: 'pro-webinar',
    name: 'Webinar signup',
    description: 'A bold, conversion-focused registration for online sessions.',
    category: 'Business',
    keywords: ['webinar', 'workshop', 'online event', 'registration', 'livestream'],
    title: 'Live: Scaling without chaos',
    formDescription: 'Thursday, 5 PM UTC · 45 minutes · Free. Can not make it? Register for the recording.',
    submitLabel: 'Save my spot',
    fields: [
      fullName(),
      email('Work email', true, 'you@company.com'),
      row([field('text', { label: 'Company', placeholder: 'Optional' })], [pick('Role', ['Founder', 'Manager', 'Individual contributor', 'Student', 'Other'])]),
      longText('A question for the speakers?', 'We will answer the best ones live.'),
    ],
    theme: look('volt', { accentColor: '#facc15', pageBg: '#facc15' }),
  },
];
