import type { FormTemplate } from '../types';
import { field, pageBreak, row } from '../types';
import { email, fullName, look, longText, multiPills, phone, pick, pills } from '../proKit';

export const proPeopleTemplates: FormTemplate[] = [
  {
    id: 'pro-employee-onboarding',
    name: 'New hire onboarding',
    description: 'Everything HR needs before day one, in three calm steps.',
    category: 'HR',
    keywords: ['onboarding', 'new hire', 'employee', 'hr', 'joining'],
    title: 'Welcome to the team',
    formDescription: 'Help us get your laptop, accounts and payroll ready before you start.',
    submitLabel: 'Complete onboarding',
    stepIndicator: 'stepper',
    showStepHeadings: true,
    steps: [
      { title: 'Personal', description: 'The basics.' },
      { title: 'Setup', description: 'Equipment and preferences.' },
      { title: 'Emergency', description: 'Who to contact if needed.' },
    ],
    fields: [
      fullName('Legal name'),
      row([email('Personal email')], [phone('Mobile', true)]),
      row([field('date', { label: 'Start date', required: true })], [field('date', { label: 'Date of birth' })]),
      field('address', { label: 'Home address', required: true }),
      pageBreak(),
      pills('Laptop', ['MacBook Pro', 'MacBook Air', 'Windows'], { required: true }),
      pick('T-shirt size', ['XS', 'S', 'M', 'L', 'XL', 'XXL']),
      longText('Accessibility needs or preferences', 'Anything that helps you do your best work.'),
      pageBreak(),
      fullName('Emergency contact'),
      row([field('text', { label: 'Relationship', required: true, placeholder: 'Partner' })], [phone('Phone', true)]),
      field('signature', { label: 'Signature', required: true }),
    ],
    theme: look('studio'),
  },
  {
    id: 'pro-employee-pulse',
    name: 'Team pulse survey',
    description: 'A short, anonymous engagement check-in for managers.',
    category: 'HR',
    keywords: ['engagement', 'pulse', 'survey', 'morale', 'wellbeing', 'enps'],
    title: 'Monthly pulse',
    formDescription: 'Anonymous. Five questions, about two minutes.',
    submitLabel: 'Submit anonymously',
    fields: [
      field('nps', { label: 'How likely are you to recommend working here to a friend?', required: true }),
      field('rating', { label: 'How was your workload this month?', required: true, maxRating: 5 }),
      pills('Do you have what you need to do your job?', ['Yes', 'Mostly', 'Not really'], { required: true }),
      longText('What is one thing we should start doing?', 'Be specific — it helps.'),
      longText('What is one thing we should stop doing?', 'Optional'),
    ],
    theme: look('sand', { accentColor: '#4d7c0f' }),
  },
  {
    id: 'pro-time-off',
    name: 'Time off request',
    description: 'A simple leave request with dates, type and cover.',
    category: 'HR',
    keywords: ['leave', 'pto', 'vacation', 'holiday', 'absence'],
    title: 'Request time off',
    formDescription: 'Submit at least two weeks ahead for planned leave.',
    submitLabel: 'Send request',
    fields: [
      fullName('Your name'),
      row([email('Work email')], [pick('Team', ['Engineering', 'Design', 'Sales', 'Marketing', 'Operations', 'Other'])]),
      pills('Type of leave', ['Vacation', 'Sick', 'Personal', 'Parental', 'Other'], { required: true }),
      field('dateRange', { label: 'Dates', required: true }),
      field('text', { label: 'Who is covering for you?', placeholder: 'Name of colleague' }),
      longText('Notes', 'Anything your manager should know.'),
    ],
    theme: look('indigo-pro', { accentColor: '#2563eb' }),
  },
  {
    id: 'pro-exit-survey',
    name: 'Exit interview',
    description: 'A respectful, candid exit survey that people actually complete.',
    category: 'HR',
    keywords: ['exit', 'offboarding', 'leaving', 'resignation', 'feedback'],
    title: 'Before you go',
    formDescription: 'Thank you for everything. Your honest answers help us become a better place to work.',
    submitLabel: 'Share feedback',
    fields: [
      pick('Main reason for leaving', ['Career growth', 'Compensation', 'Manager', 'Culture', 'Relocation', 'Personal', 'Other'], { required: true }),
      field('rating', { label: 'Overall experience working here', maxRating: 5, required: true }),
      longText('What did we do well?', 'The things worth keeping.'),
      longText('What should we improve?', 'The things worth fixing.'),
      pills('Would you consider coming back?', ['Yes', 'Maybe', 'No']),
    ],
    theme: look('editorial', { accentColor: '#7c2d12' }),
  },
  {
    id: 'pro-course-application',
    name: 'Program application',
    description: 'An admissions-grade application for courses, cohorts and bootcamps.',
    category: 'Education',
    keywords: ['admissions', 'course', 'bootcamp', 'cohort', 'application', 'school'],
    title: 'Apply to the Spring cohort',
    formDescription: '12 weeks, part-time, fully remote. Applications close March 1.',
    submitLabel: 'Submit application',
    stepIndicator: 'progress',
    showStepHeadings: true,
    steps: [
      { title: 'About you', description: 'Your contact details.' },
      { title: 'Background', description: 'Where you are starting from.' },
      { title: 'Motivation', description: 'Why now, and why this.' },
    ],
    fields: [
      fullName(),
      row([email()], [phone()]),
      row([field('country', { label: 'Country', required: true })], [field('date', { label: 'Date of birth' })]),
      pageBreak(),
      pick('Highest education', ['High school', 'Diploma', "Bachelor's", "Master's", 'Doctorate', 'Other'], { required: true }),
      pills('Current status', ['Student', 'Employed', 'Self-employed', 'Between jobs'], { required: true }),
      field('website', { label: 'LinkedIn or portfolio', placeholder: 'linkedin.com/in/you' }),
      pageBreak(),
      longText('Why do you want to join?', 'What you hope to learn and what you will do with it.', true),
      pills('Can you commit 10 hours a week?', ['Yes', 'No'], { required: true }),
      field('terms', { label: 'I agree to the program terms', required: true }),
    ],
    theme: look('studio', { accentColor: '#7c3aed' }),
  },
  {
    id: 'pro-course-feedback',
    name: 'Course evaluation',
    description: 'End-of-course feedback on content, pacing and instruction.',
    category: 'Education',
    keywords: ['course', 'evaluation', 'feedback', 'teacher', 'class', 'training'],
    title: 'How was the course?',
    formDescription: 'Your feedback shapes the next cohort. Takes three minutes.',
    submitLabel: 'Submit evaluation',
    fields: [
      pick('Which course did you take?', ['Foundations', 'Intermediate', 'Advanced', 'Workshop'], { required: true }),
      field('rating', { label: 'Overall rating', required: true, maxRating: 5 }),
      pills('Pacing', ['Too slow', 'Just right', 'Too fast'], { required: true }),
      field('rating', { label: 'Instructor clarity', maxRating: 5 }),
      longText('Most valuable part', 'What will you actually use?'),
      longText('What would you change?', 'Optional'),
    ],
    theme: look('blush', { accentColor: '#7c3aed', pageBg: '#f5f3ff', inputBorder: '#ddd6fe', cardBorder: '#ede9fe', labelColor: '#2e1065', inputTextColor: '#2e1065', inputBg: '#faf8ff', pageBackground: { gradient: 'linear-gradient(160deg, #ede9fe 0%, #fdf4ff 100%)' } }),
  },
  {
    id: 'pro-tutor-booking',
    name: 'Tutoring session',
    description: 'Book a one-to-one session with subject, level and time.',
    category: 'Education',
    keywords: ['tutor', 'lesson', 'booking', 'student', 'class'],
    title: 'Book a session',
    formDescription: 'Sessions are 60 minutes, online or in person.',
    submitLabel: 'Request session',
    fields: [
      fullName('Student name'),
      row([email()], [phone()]),
      row([pick('Subject', ['Maths', 'Physics', 'Chemistry', 'English', 'Coding', 'Other'], { required: true })], [pick('Level', ['Primary', 'Middle school', 'High school', 'University', 'Adult'])]),
      row([field('date', { label: 'Preferred date', required: true })], [field('time', { label: 'Preferred time', required: true })]),
      pills('Format', ['Online', 'In person'], { required: true }),
      longText('What would you like to focus on?', 'Topics, upcoming exams, or homework.'),
    ],
    theme: look('sand', { accentColor: '#0369a1' }),
  },
  {
    id: 'pro-volunteer',
    name: 'Volunteer signup',
    description: 'Recruit volunteers with availability and interests, in a warm tone.',
    category: 'Community',
    keywords: ['volunteer', 'nonprofit', 'charity', 'community', 'helpers'],
    title: 'Volunteer with us',
    formDescription: 'An hour or a weekend — every bit of help makes a difference.',
    submitLabel: 'Sign me up',
    fields: [
      fullName(),
      row([email()], [phone('Phone', true)]),
      multiPills('Where would you like to help?', ['Events', 'Outreach', 'Fundraising', 'Admin', 'Mentoring', 'Anywhere'], { required: true }),
      multiPills('Availability', ['Weekday mornings', 'Weekday evenings', 'Weekends']),
      longText('Skills or experience', 'Languages, first aid, design, driving…'),
      field('terms', { label: 'I agree to the volunteer code of conduct', required: true }),
    ],
    theme: look('blush', { accentColor: '#ea580c', pageBg: '#fff7ed', cardBorder: '#ffedd5', inputBorder: '#fed7aa', inputBg: '#fffbf5', labelColor: '#431407', inputTextColor: '#431407', pageBackground: { gradient: 'linear-gradient(160deg, #ffedd5 0%, #fff7ed 100%)' } }),
  },
  {
    id: 'pro-membership',
    name: 'Membership application',
    description: 'A refined members-club application with tiers and referrals.',
    category: 'Community',
    keywords: ['membership', 'club', 'society', 'association', 'join'],
    title: 'Membership',
    formDescription: 'Applications are reviewed monthly by the membership committee.',
    submitLabel: 'Apply for membership',
    fields: [
      fullName(),
      row([email()], [phone()]),
      row([field('text', { label: 'Occupation', placeholder: 'Architect' })], [field('text', { label: 'City', placeholder: 'London' })]),
      pills('Membership tier', ['Individual', 'Couple', 'Corporate'], { required: true }),
      field('text', { label: 'Referred by', placeholder: 'Name of an existing member' }),
      longText('Why would you like to join?', 'A few sentences is plenty.'),
    ],
    theme: look('studio-dark', { accentColor: '#d4af37', fontFamily: 'playfair', titleSize: 'xl' }),
  },
  {
    id: 'pro-community-feedback',
    name: 'Community survey',
    description: 'Gauge what members want next — topics, formats and frequency.',
    category: 'Community',
    keywords: ['community', 'survey', 'members', 'feedback', 'discord', 'slack'],
    title: 'Shape the community',
    formDescription: 'Help us plan the next six months. Two minutes, promise.',
    submitLabel: 'Submit',
    fields: [
      pills('How long have you been a member?', ['< 3 months', '3–12 months', '1 year+'], { required: true }),
      multiPills('What would you like more of?', ['Workshops', 'AMAs', 'Meetups', 'Challenges', 'Job board', 'Resources']),
      pills('How often should we host events?', ['Weekly', 'Biweekly', 'Monthly']),
      field('nps', { label: 'How likely are you to invite a friend?' }),
      longText('Anything else?', 'Ideas, gripes, or praise.'),
    ],
    theme: look('graphite', { accentColor: '#a855f7' }),
  },
];
