import type { FormTemplate } from '../types';
import { field, pageBreak, row } from '../types';
import { email, fullName, look, longText, multiPills, phone, pick, pills } from '../proKit';

const CLINIC = {
  accentColor: '#0d9488',
  pageBg: '#f0fdfa',
  cardBorder: '#ccfbf1',
  inputBg: '#f0fdfa',
  inputBorder: '#f0fdfa',
  labelColor: '#134e4a',
  inputTextColor: '#134e4a',
};

export const proServicesTemplates: FormTemplate[] = [
  {
    id: 'pro-patient-intake',
    name: 'Patient intake',
    description: 'A calm, three-step intake for clinics, therapists and practitioners.',
    category: 'Health',
    keywords: ['patient', 'clinic', 'medical', 'intake', 'therapy', 'doctor'],
    title: 'New patient form',
    formDescription: 'Please complete before your first visit. Your information is kept confidential.',
    submitLabel: 'Submit form',
    stepIndicator: 'stepper',
    showStepHeadings: true,
    steps: [
      { title: 'Details', description: 'How we can reach you.' },
      { title: 'Health', description: 'A little medical history.' },
      { title: 'Consent', description: 'Review and sign.' },
    ],
    fields: [
      fullName(),
      row([field('date', { label: 'Date of birth', required: true })], [phone('Phone', true)]),
      email(),
      field('address', { label: 'Address' }),
      pageBreak(),
      longText('Reason for visit', 'Symptoms, concerns, or goals.', true),
      longText('Current medications', 'Name and dose, or "None".'),
      field('text', { label: 'Allergies', placeholder: 'e.g. Penicillin, or none' }),
      pills('Have you been seen here before?', ['Yes', 'No'], { required: true }),
      pageBreak(),
      fullName('Emergency contact', false),
      phone('Emergency phone'),
      field('terms', { label: 'I consent to treatment and to the privacy policy', required: true }),
      field('signature', { label: 'Signature', required: true }),
    ],
    theme: look('studio', CLINIC),
  },
  {
    id: 'pro-appointment',
    name: 'Appointment booking',
    description: 'A soft, reassuring booking form for wellness and beauty studios.',
    category: 'Health',
    keywords: ['appointment', 'booking', 'spa', 'salon', 'wellness', 'massage'],
    title: 'Book an appointment',
    formDescription: 'We will confirm by text within a few hours.',
    submitLabel: 'Request booking',
    fields: [
      pick('Service', ['Consultation · 30 min', 'Massage · 60 min', 'Facial · 45 min', 'Physio · 45 min'], { required: true }),
      row([field('date', { label: 'Date', required: true })], [field('time', { label: 'Time', required: true })]),
      pills('Practitioner', ['No preference', 'Alex', 'Sam', 'Priya']),
      fullName(),
      row([phone('Phone', true)], [email('Email', false)]),
      longText('Anything we should know?', 'Injuries, sensitivities, or preferences.'),
    ],
    theme: look('sand', { accentColor: '#9a3412' }),
  },
  {
    id: 'pro-property-viewing',
    name: 'Property viewing',
    description: 'A premium viewing request for estate agents and developers.',
    category: 'Real estate',
    keywords: ['property', 'viewing', 'real estate', 'house', 'apartment', 'showing'],
    title: 'Book a viewing',
    formDescription: '14 Harbour Lane · 3 bed · 2 bath. Viewings run Monday to Saturday.',
    submitLabel: 'Request viewing',
    fields: [
      fullName(),
      row([email()], [phone('Phone', true)]),
      row([field('date', { label: 'Preferred date', required: true })], [pills('Time of day', ['Morning', 'Afternoon', 'Evening'])]),
      pills('Are you buying or renting?', ['Buying', 'Renting'], { required: true }),
      pick('Position', ['First-time buyer', 'Have a property to sell', 'Sold, ready to move', 'Investor', 'Cash buyer']),
      pills('Mortgage in principle?', ['Yes', 'No', 'In progress']),
    ],
    theme: look('studio-dark', { accentColor: '#e5c07b', fontFamily: 'manrope' }),
  },
  {
    id: 'pro-rental-application',
    name: 'Rental application',
    description: 'Tenant screening in three steps: applicant, income and references.',
    category: 'Real estate',
    keywords: ['rental', 'tenant', 'lease', 'apartment', 'screening', 'landlord'],
    title: 'Rental application',
    formDescription: 'One form per adult applicant. Decisions within 48 hours.',
    submitLabel: 'Submit application',
    stepIndicator: 'progress',
    showStepHeadings: true,
    steps: [
      { title: 'Applicant', description: 'Your details.' },
      { title: 'Income', description: 'Employment and affordability.' },
      { title: 'References', description: 'Previous landlord.' },
    ],
    fields: [
      fullName(),
      row([email()], [phone('Phone', true)]),
      row([field('date', { label: 'Move-in date', required: true })], [pick('Lease length', ['6 months', '12 months', '18 months', '24 months'])]),
      pills('Pets?', ['None', 'Cat', 'Dog', 'Other']),
      pageBreak(),
      pills('Employment status', ['Employed', 'Self-employed', 'Student', 'Retired'], { required: true }),
      row([field('text', { label: 'Employer', placeholder: 'Company name' })], [field('currency', { label: 'Annual income', required: true })]),
      field('file', { label: 'Proof of income', helpText: 'Payslips or an offer letter.' }),
      pageBreak(),
      fullName('Previous landlord', false),
      row([phone('Landlord phone')], [email('Landlord email', false)]),
      field('terms', { label: 'I consent to a credit and reference check', required: true }),
    ],
    theme: look('indigo-pro', { accentColor: '#0f766e' }),
  },
  {
    id: 'pro-hotel-booking',
    name: 'Stay enquiry',
    description: 'A boutique-hotel enquiry with dates, room and guest details.',
    category: 'Hospitality',
    keywords: ['hotel', 'stay', 'booking', 'room', 'resort', 'villa'],
    title: 'Plan your stay',
    formDescription: 'Tell us when you would like to visit and we will hold the best room available.',
    submitLabel: 'Send enquiry',
    fields: [
      field('dateRange', { label: 'Check-in and check-out', required: true }),
      row([pick('Adults', ['1', '2', '3', '4', '5', '6'], { required: true })], [pick('Children', ['0', '1', '2', '3', '4'])]),
      pills('Room', ['Garden', 'Sea view', 'Suite'], { required: true }),
      fullName(),
      row([email()], [phone()]),
      multiPills('Add to your stay', ['Airport transfer', 'Spa', 'Breakfast', 'Late checkout']),
      longText('Special requests', 'Celebrations, accessibility, dietary needs…'),
    ],
    theme: look('editorial', { fontFamily: 'playfair', accentColor: '#1e3a8a', pageBg: '#f8f6f1', cardBg: '#f8f6f1', cardBorder: '#f8f6f1', inputBg: '#f8f6f1' }),
  },
  {
    id: 'pro-catering',
    name: 'Catering request',
    description: 'Collect event size, menu style and dietary needs for catering quotes.',
    category: 'Hospitality',
    keywords: ['catering', 'event', 'food', 'menu', 'party', 'wedding'],
    title: 'Catering enquiry',
    formDescription: 'From office lunches to weddings. We reply with a tailored menu and quote.',
    submitLabel: 'Request a menu',
    fields: [
      fullName(),
      row([email()], [phone('Phone', true)]),
      row([field('date', { label: 'Event date', required: true })], [field('number', { label: 'Guests', required: true, placeholder: '50' })]),
      pills('Style', ['Buffet', 'Plated', 'Canapés', 'Family style'], { required: true }),
      multiPills('Dietary needs', ['Vegetarian', 'Vegan', 'Gluten free', 'Halal', 'Nut free']),
      field('address', { label: 'Venue address' }),
      longText('Anything else?', 'Theme, budget, or must-have dishes.'),
    ],
    theme: look('sand', { accentColor: '#166534' }),
  },
  {
    id: 'pro-order',
    name: 'Product order',
    description: 'A clean order form with quantity, delivery and notes.',
    category: 'Commerce',
    keywords: ['order', 'purchase', 'shop', 'product', 'checkout', 'wholesale'],
    title: 'Place an order',
    formDescription: 'Orders placed before 2 PM ship the same day.',
    submitLabel: 'Place order',
    fields: [
      row([pick('Product', ['Classic Tee', 'Heavyweight Hoodie', 'Canvas Tote', 'Cap'], { required: true })], [field('number', { label: 'Quantity', required: true, placeholder: '1' })]),
      pills('Size', ['XS', 'S', 'M', 'L', 'XL']),
      pills('Colour', ['Black', 'White', 'Sand', 'Navy']),
      fullName(),
      row([email()], [phone()]),
      field('address', { label: 'Delivery address', required: true }),
      pills('Delivery', ['Standard', 'Express']),
      longText('Order notes', 'Gift message or delivery instructions.'),
    ],
    theme: look('studio', { accentColor: '#111111', fontFamily: 'dmSans' }),
  },
  {
    id: 'pro-return',
    name: 'Return request',
    description: 'A friendly returns form with reason codes and photo upload.',
    category: 'Commerce',
    keywords: ['return', 'refund', 'exchange', 'rma', 'ecommerce'],
    title: 'Start a return',
    formDescription: 'Returns are free within 30 days of delivery.',
    submitLabel: 'Submit return',
    fields: [
      row([field('text', { label: 'Order number', required: true, placeholder: '#10482' })], [email('Email used for the order')]),
      field('text', { label: 'Item', required: true, placeholder: 'Heavyweight Hoodie, Sand, M' }),
      pick('Reason', ['Too small', 'Too large', 'Damaged', 'Not as described', 'Changed my mind', 'Other'], { required: true }),
      pills('What would you like?', ['Refund', 'Exchange', 'Store credit'], { required: true }),
      field('imageUpload', { label: 'Photo of the item', helpText: 'Required for damaged items.' }),
      longText('Anything else?', 'Optional'),
    ],
    theme: look('blush', { accentColor: '#be185d' }),
  },
  {
    id: 'pro-support-ticket',
    name: 'Support ticket',
    description: 'A modern help-desk form with priority, product area and attachments.',
    category: 'Support',
    keywords: ['support', 'ticket', 'help', 'issue', 'helpdesk', 'customer service'],
    title: 'How can we help?',
    formDescription: 'Our team typically replies within four business hours.',
    submitLabel: 'Submit ticket',
    fields: [
      fullName('Name'),
      email(),
      row([pick('Product area', ['Account & billing', 'Getting started', 'Integrations', 'Bug', 'Other'], { required: true })], [pills('Priority', ['Low', 'Normal', 'Urgent'])]),
      field('text', { label: 'Subject', required: true, placeholder: 'Cannot connect my calendar' }),
      longText('Describe the issue', 'What happened, what you expected, and any error messages.', true),
      field('file', { label: 'Attachment', helpText: 'Screenshots or logs.' }),
    ],
    theme: look('indigo-pro', { accentColor: '#2563eb' }),
  },
  {
    id: 'pro-feature-request',
    name: 'Feature request',
    description: 'Capture product ideas with impact and urgency, in a dark product style.',
    category: 'Support',
    keywords: ['feature', 'request', 'idea', 'roadmap', 'feedback', 'product'],
    title: 'Suggest a feature',
    formDescription: 'We read every request. The most-requested ideas go on the public roadmap.',
    submitLabel: 'Submit idea',
    fields: [
      field('text', { label: 'Your idea in one line', required: true, placeholder: 'Export dashboards as PDF' }),
      longText('What problem does it solve?', 'Describe the job you are trying to get done.', true),
      pills('How important is this?', ['Nice to have', 'Important', 'Blocking'], { required: true }),
      multiPills('Area', ['Dashboard', 'Reports', 'Integrations', 'Mobile', 'API']),
      email('Email', false, 'For updates on this idea'),
    ],
    theme: look('graphite'),
  },
];
