import type { FormTemplate } from './types';
import { field, row } from './types';

/** The everyday forms — a contact box, a signup, an RSVP. */
export const basicTemplates: FormTemplate[] = [
  {
    id: 'blank',
    name: 'Blank form',
    description: 'Start from scratch with an empty canvas.',
    category: 'Basics',
    title: 'Untitled form',
    fields: [],
  },
  {
    id: 'contact',
    name: 'Contact form',
    description: 'Name, email, subject, and message on a clean light card.',
    category: 'Basics',
    keywords: ['get in touch', 'enquiry', 'message', 'support'],
    title: 'Contact us',
    formDescription: "Tell us what you need and we'll come back within one business day.",
    submitLabel: 'Send message',
    fields: [
      row(
        [field('name', { label: 'Full name', required: true, placeholder: 'Ada Lovelace' })],
        [field('email', { label: 'Email', required: true, placeholder: 'ada@example.com' })]
      ),
      field('select', {
        label: 'What is this about?',
        required: true,
        options: ['General enquiry', 'Sales', 'Support', 'Partnerships', 'Something else'],
      }),
      field('textarea', { label: 'Message', required: true, placeholder: 'How can we help?' }),
      field('decisionBox', { label: 'Send me occasional product updates' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#f8fafc',
      cardBg: '#ffffff',
      cardBorder: '#e2e8f0',
      accentColor: '#0f172a',
      labelColor: '#0f172a',
      inputBg: '#ffffff',
      inputBorder: '#cbd5e1',
      inputTextColor: '#0f172a',
      textMode: 'dark',
      cardRadius: 14,
      cardShadow: 'lg',
      fontFamily: 'inter',
      pageBackground: { gradient: 'linear-gradient(160deg, #eef2f7 0%, #f8fafc 60%)' },
    },
  },
  {
    id: 'feedback',
    name: 'Feedback survey',
    description: 'A rating scale plus open comments, on a warm light card.',
    category: 'Basics',
    keywords: ['review', 'rating', 'survey', 'experience'],
    title: 'We would love your feedback',
    formDescription: 'Takes less than a minute, and we read every one.',
    submitLabel: 'Send feedback',
    fields: [
      field('rating', { label: 'How would you rate your experience?', required: true, maxRating: 5 }),
      field('radio', {
        label: 'Would you recommend us to a friend?',
        required: true,
        options: ['Yes', 'No', 'Not sure'],
      }),
      field('textarea', { label: 'Anything else you want to share?', placeholder: 'Optional comments' }),
      field('email', { label: 'Email', helpText: 'Only if you would like a reply.' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#fffbf5',
      cardBg: '#ffffff',
      cardBorder: '#f1e5d6',
      accentColor: '#c2410c',
      labelColor: '#431407',
      inputBg: '#fffdfa',
      inputBorder: '#f1e5d6',
      inputTextColor: '#431407',
      textMode: 'dark',
      cardRadius: 18,
      cardShadow: 'md',
      fontFamily: 'rounded',
      pageBackground: { gradient: 'linear-gradient(150deg, #ffedd5 0%, #fffbf5 65%)' },
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter signup',
    description: 'Name, email, and topic picks — a proper subscribe card, not a bare input.',
    category: 'Basics',
    keywords: ['subscribe', 'email list', 'marketing', 'digest'],
    title: 'The weekly digest',
    formDescription: 'One email each Friday: what shipped, what we learned, what is next. Unsubscribe in a click.',
    submitLabel: 'Subscribe',
    fields: [
      row(
        [field('name', { label: 'First name', required: true, placeholder: 'Ada' })],
        [field('email', { label: 'Email', required: true, placeholder: 'you@company.com' })]
      ),
      field('checkbox', {
        label: 'What should we send you?',
        options: ['Product updates', 'Engineering write-ups', 'Events and webinars', 'Offers'],
      }),
      field('terms', { label: 'I agree to receive email and accept the privacy policy', required: true }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#09090b',
      cardBg: '#131318',
      cardBorder: '#26262e',
      accentColor: '#14b8a6',
      labelColor: '#e4e4e7',
      inputBg: '#0e0e12',
      inputBorder: '#2a2a33',
      inputTextColor: '#fafafa',
      textMode: 'light',
      cardRadius: 16,
      cardShadow: 'xl',
      fontFamily: 'inter',
      pageBackground: {
        gradient: 'radial-gradient(circle at 50% -10%, #0f766e 0%, #09090b 60%)',
      },
    },
  },
  {
    id: 'rsvp',
    name: 'Event RSVP',
    description: 'Attendance, guest count, and dietary needs, on an invitation-style card.',
    category: 'Basics',
    keywords: ['invite', 'invitation', 'party', 'wedding', 'attend'],
    title: 'RSVP',
    formDescription: 'Let us know if you can make it — replies close two weeks before.',
    submitLabel: 'Send RSVP',
    fields: [
      row(
        [field('name', { label: 'Full name', required: true, placeholder: 'Ada Lovelace' })],
        [field('email', { label: 'Email', required: true, placeholder: 'ada@example.com' })]
      ),
      field('yesNo', { label: 'Will you attend?', required: true }),
      field('number', { label: 'Number of guests', min: 0, max: 10, initialValue: '1' }),
      field('textarea', { label: 'Dietary restrictions', placeholder: 'e.g. vegetarian, nut allergy' }),
      field('textarea', { label: 'A note for the hosts', placeholder: 'Optional' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#1c1917',
      cardBg: '#fffdf8',
      cardBorder: '#e7e0d3',
      accentColor: '#78350f',
      labelColor: '#292524',
      inputBg: '#ffffff',
      inputBorder: '#e7e0d3',
      inputTextColor: '#292524',
      textMode: 'dark',
      cardRadius: 4,
      cardShadow: 'xl',
      fontFamily: 'serif',
      pageBackground: {
        gradient: 'linear-gradient(160deg, #44403c 0%, #1c1917 100%)',
        overlay: '#000000',
        overlayOpacity: 15,
      },
    },
  },
  {
    id: 'waitlist',
    name: 'Waitlist signup',
    description: 'Dark, minimal signup for an early-access or coming-soon page.',
    category: 'Basics',
    keywords: ['early access', 'launch', 'coming soon', 'beta'],
    title: 'Join the waitlist',
    formDescription: "We'll email you the moment a spot opens up.",
    submitLabel: 'Join the list',
    fields: [
      field('email', { label: 'Email', required: true, placeholder: 'you@example.com' }),
      field('select', {
        label: 'How did you hear about us?',
        required: false,
        options: ['Twitter / X', 'A friend', 'Search', 'Newsletter', 'Something else'],
      }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#0a0a0f',
      cardBg: '#16161d',
      cardBorder: '#26262f',
      accentColor: '#7c5cff',
      labelColor: '#e4e4e7',
      inputBg: '#101017',
      inputBorder: '#2a2a34',
      inputTextColor: '#fafafa',
      textMode: 'light',
      cardRadius: 14,
      cardShadow: 'xl',
      fontFamily: 'inter',
      pageBackground: {
        gradient: 'radial-gradient(circle at 50% 0%, #2e1065 0%, #0a0a0f 65%)',
      },
    },
  },
];
