import type { FormTemplate } from './types';
import { field, pageBreak, row } from './types';

/** Clubs, causes, and anything run by volunteers. */
export const communityTemplates: FormTemplate[] = [
  {
    id: 'volunteerSignup',
    name: 'Volunteer signup',
    description: 'Availability, skills, and consent for a volunteer roster.',
    category: 'Community',
    keywords: ['charity', 'volunteer', 'nonprofit', 'helper', 'roster'],
    title: 'Volunteer with us',
    formDescription: 'Tell us when you are free and what you enjoy doing.',
    submitLabel: 'Sign me up',
    fields: [
      row(
        [field('name', { label: 'Full name', required: true })],
        [field('email', { label: 'Email', required: true })]
      ),
      field('phone', { label: 'Phone' }),
      field('checkbox', {
        label: 'When are you usually free?',
        required: true,
        options: ['Weekday mornings', 'Weekday afternoons', 'Weekday evenings', 'Saturdays', 'Sundays'],
      }),
      field('checkbox', {
        label: 'What would you like to help with?',
        options: ['Events', 'Fundraising', 'Admin', 'Driving', 'Outreach', 'Anything needed'],
      }),
      field('textarea', { label: 'Relevant skills or experience' }),
      field('yesNo', { label: 'Do you have a background check on file?' }),
      field('terms', { label: 'I agree to the volunteer code of conduct', required: true }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#fff7ed',
      cardBg: '#ffffff',
      cardBorder: '#fed7aa',
      accentColor: '#ea580c',
      labelColor: '#431407',
      textMode: 'dark',
      cardRadius: 16,
      cardShadow: 'md',
      fontFamily: 'rounded',
    },
  },
  {
    id: 'membershipApplication',
    name: 'Club membership',
    description: 'Member details, tier, and interests for a club or association.',
    category: 'Community',
    keywords: ['club', 'society', 'association', 'member', 'join'],
    title: 'Become a member',
    formDescription: 'Membership runs for twelve months from the day you join.',
    submitLabel: 'Apply',
    stepIndicator: 'dots',
    steps: [{ title: 'You' }, { title: 'Membership' }],
    fields: [
      row(
        [field('name', { label: 'Full name', required: true })],
        [field('email', { label: 'Email', required: true })]
      ),
      field('address', { label: 'Address' }),
      field('date', { label: 'Date of birth' }),
      pageBreak(),
      field('radio', {
        label: 'Membership tier',
        required: true,
        options: ['Standard', 'Concession', 'Family', 'Life member'],
      }),
      field('checkbox', {
        label: 'Interests',
        options: ['Meetups', 'Competitions', 'Workshops', 'Newsletter only'],
      }),
      field('text', { label: 'Proposed by', helpText: 'An existing member, if you have one.' }),
      field('decisionBox', { label: 'Show my name in the member directory' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#0f172a',
      cardBg: '#1e293b',
      cardBorder: '#334155',
      accentColor: '#facc15',
      labelColor: '#e2e8f0',
      inputBg: '#172033',
      inputBorder: '#334155',
      inputTextColor: '#f8fafc',
      textMode: 'light',
      cardRadius: 12,
      cardShadow: 'lg',
      fontFamily: 'inter',
    },
  },
  {
    id: 'petitionSignature',
    name: 'Petition signature',
    description: 'Name, postcode, and an optional comment — a one-screen sign-on.',
    category: 'Community',
    keywords: ['campaign', 'petition', 'sign', 'advocacy'],
    title: 'Add your name',
    formDescription: 'Signatures are delivered to the council at the end of the month.',
    submitLabel: 'Sign',
    fields: [
      row(
        [field('name', { label: 'Full name', required: true })],
        [field('email', { label: 'Email', required: true, unique: true })]
      ),
      field('text', { label: 'Postcode', required: true, placeholder: 'SW1A 1AA' }),
      field('textarea', { label: 'Why this matters to you', placeholder: 'Optional — may be published.' }),
      field('decisionBox', { label: 'Email me campaign updates' }),
      field('terms', { label: 'I confirm I am eligible to sign', required: true }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#450a0a',
      cardBg: '#ffffff',
      cardBorder: '#fecaca',
      accentColor: '#b91c1c',
      labelColor: '#450a0a',
      textMode: 'dark',
      cardRadius: 8,
      cardShadow: 'xl',
      fontFamily: 'inter',
      pageBackground: { gradient: 'linear-gradient(135deg, #7f1d1d 0%, #450a0a 100%)' },
    },
  },
  {
    id: 'contestEntry',
    name: 'Contest entry',
    description: 'Entrant details, submission upload, and rules acceptance.',
    category: 'Community',
    keywords: ['competition', 'giveaway', 'entry', 'submission', 'prize'],
    title: 'Enter the contest',
    formDescription: 'One entry per person. Winners announced two weeks after closing.',
    submitLabel: 'Enter',
    fields: [
      row(
        [field('name', { label: 'Your name', required: true })],
        [field('email', { label: 'Email', required: true, unique: true })]
      ),
      field('select', {
        label: 'Category',
        required: true,
        options: ['Photography', 'Writing', 'Illustration', 'Video', 'Open'],
      }),
      field('text', { label: 'Title of your entry', required: true }),
      field('textarea', { label: 'Describe your entry', maxLength: 500 }),
      field('mediaUpload', { label: 'Your submission', required: true }),
      field('terms', { label: 'I have read and accept the contest rules', required: true }),
      field('decisionBox', { label: 'You may share my entry on social media' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#1e1b4b',
      cardBg: '#ffffff',
      cardBorder: '#ddd6fe',
      accentColor: '#db2777',
      labelColor: '#1e1b4b',
      textMode: 'dark',
      cardRadius: 20,
      cardShadow: 'xl',
      fontFamily: 'rounded',
      pageBackground: {
        gradient: 'linear-gradient(135deg, #f472b6 0%, #818cf8 100%)',
        overlay: '#000000',
        overlayOpacity: 15,
      },
    },
  },
];
