import type { FormTemplate } from './types';
import { field, pageBreak, repeater, row } from './types';

/** Surveys and structured feedback — the forms built around scales and grids. */
export const feedbackTemplates: FormTemplate[] = [
  {
    id: 'npsSurvey',
    name: 'NPS survey',
    description: 'A single recommendation score, a reason, and a follow-up opt-in.',
    category: 'Support',
    keywords: ['nps', 'net promoter', 'loyalty', 'score', 'survey'],
    title: 'How are we doing?',
    formDescription: 'One question that matters, and space to tell us why.',
    submitLabel: 'Send',
    fields: [
      field('nps', { label: 'How likely are you to recommend us to a friend or colleague?', required: true }),
      field('textarea', {
        label: 'What is the main reason for your score?',
        required: true,
        placeholder: 'The more specific, the more useful.',
      }),
      field('likert', {
        label: 'How easy was it to get what you needed?',
        options: ['Very hard', 'Hard', 'Neutral', 'Easy', 'Very easy'],
      }),
      field('yesNo', { label: 'May we follow up on your answers?' }),
      field('email', { label: 'Email', placeholder: 'Only if you said yes' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#f0fdf4',
      cardBg: '#ffffff',
      cardBorder: '#bbf7d0',
      accentColor: '#16a34a',
      labelColor: '#14532d',
      inputBg: '#ffffff',
      inputBorder: '#bbf7d0',
      inputTextColor: '#14532d',
      textMode: 'dark',
      cardRadius: 14,
      cardShadow: 'md',
      fontFamily: 'inter',
    },
  },
  {
    id: 'productFeedback',
    name: 'Product feedback',
    description: 'Agreement scales across quality, value and support, plus a wishlist.',
    category: 'Support',
    keywords: ['feedback', 'product', 'csat', 'likert', 'review'],
    title: 'Tell us what you think',
    formDescription: 'Three minutes, and it shapes what we build next.',
    submitLabel: 'Send feedback',
    fields: [
      field('likert', {
        label: 'The product does what I need it to do',
        required: true,
      }),
      field('likert', {
        label: 'It is good value for the money',
        required: true,
      }),
      field('likert', {
        label: 'Support answers quickly and helpfully',
        options: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree', 'Have not needed it'],
      }),
      field('nps', { label: 'Overall, how likely are you to recommend it?', required: true }),
      repeater('Features you wish it had', [
        field('text', { label: 'Feature', required: true }),
        field('textarea', { label: 'Why it matters to you' }),
      ]),
      field('textarea', { label: 'Anything else?', placeholder: 'Optional' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#1e293b',
      cardBg: '#ffffff',
      cardBorder: '#e2e8f0',
      accentColor: '#6366f1',
      labelColor: '#0f172a',
      inputBg: '#f8fafc',
      inputBorder: '#cbd5e1',
      inputTextColor: '#0f172a',
      textMode: 'dark',
      cardRadius: 16,
      cardShadow: 'xl',
      fontFamily: 'inter',
      pageBackground: { gradient: 'linear-gradient(160deg, #312e81 0%, #1e293b 100%)' },
    },
  },
  {
    id: 'venueBooking',
    name: 'Venue booking',
    description: 'A date range, a time range, headcount, and setup requirements.',
    category: 'Hospitality',
    keywords: ['booking', 'venue', 'event', 'hire', 'date range', 'room'],
    title: 'Book the space',
    formDescription: 'Send the details and we confirm availability within a day.',
    submitLabel: 'Request booking',
    stepIndicator: 'dots',
    steps: [{ title: 'When' }, { title: 'What you need' }],
    fields: [
      field('dateRange', { label: 'Dates', required: true }),
      field('timeRange', { label: 'Hours on each day', required: true }),
      field('select', {
        label: 'Space',
        required: true,
        options: ['Main hall', 'Meeting room', 'Studio', 'Outdoor area', 'Whole venue'],
      }),
      pageBreak(),
      field('number', { label: 'Expected headcount', required: true, min: 1, max: 2000 }),
      field('checkbox', {
        label: 'Setup needed',
        options: ['Seating', 'Stage', 'AV / projector', 'Catering', 'Parking', 'Accessibility ramp'],
      }),
      repeater('Add-ons', [
        field('text', { label: 'Item', required: true }),
        field('number', { label: 'Quantity', min: 1 }),
      ]),
      row(
        [field('name', { label: 'Contact name', required: true })],
        [field('email', { label: 'Email', required: true })]
      ),
      field('phone', { label: 'Phone', required: true }),
      field('textarea', { label: 'Anything else we should know?' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#fef3c7',
      cardBg: '#ffffff',
      cardBorder: '#fde68a',
      accentColor: '#d97706',
      labelColor: '#78350f',
      inputBg: '#fffbeb',
      inputBorder: '#fde68a',
      inputTextColor: '#78350f',
      textMode: 'dark',
      cardRadius: 16,
      cardShadow: 'lg',
      fontFamily: 'rounded',
      pageBackground: {
        gradient: 'linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)',
        overlay: '#ffffff',
        overlayOpacity: 55,
      },
    },
  },
  {
    id: 'trainingBooking',
    name: 'Training booking',
    description: 'Course dates, session times, and one row per attendee.',
    category: 'Education',
    keywords: ['training', 'course', 'workshop', 'attendees', 'booking', 'schedule'],
    title: 'Book a training session',
    formDescription: 'Add every attendee — each gets their own joining details.',
    submitLabel: 'Book',
    fields: [
      field('select', {
        label: 'Course',
        required: true,
        options: ['Onboarding basics', 'Advanced workflows', 'Admin and security', 'Train the trainer'],
      }),
      field('dateRange', { label: 'Preferred dates', required: true }),
      field('timeRange', { label: 'Preferred hours' }),
      field('radio', {
        label: 'Delivery',
        required: true,
        options: ['On site', 'Remote', 'Hybrid'],
      }),
      repeater(
        'Attendees',
        [
          field('name', { label: 'Name', required: true }),
          field('email', { label: 'Email', required: true }),
          field('text', { label: 'Role' }),
          field('text', { label: 'Access needs' }),
        ],
        { required: true, minRows: 1 }
      ),
      row(
        [field('name', { label: 'Booking contact', required: true })],
        [field('email', { label: 'Contact email', required: true })]
      ),
      field('textarea', { label: 'Goals for the session', placeholder: 'What should people be able to do afterwards?' }),
      field('terms', { label: 'I accept the booking terms', required: true }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#eef2ff',
      cardBg: '#ffffff',
      cardBorder: '#c7d2fe',
      accentColor: '#4f46e5',
      labelColor: '#1e1b4b',
      inputBg: '#ffffff',
      inputBorder: '#c7d2fe',
      inputTextColor: '#1e1b4b',
      textMode: 'dark',
      cardRadius: 14,
      cardShadow: 'lg',
      fontFamily: 'inter',
      pageBackground: { gradient: 'linear-gradient(150deg, #e0e7ff 0%, #f5f3ff 100%)' },
    },
  },
  {
    id: 'patientIntake',
    name: 'Patient intake',
    description: 'Contact details, current medications, and a symptom check-in scale.',
    category: 'Health',
    keywords: ['intake', 'patient', 'medical', 'symptoms', 'medication', 'clinic'],
    title: 'Before your appointment',
    formDescription: 'Fill this in so your clinician has what they need on the day.',
    submitLabel: 'Submit',
    stepIndicator: 'progress',
    showStepHeadings: true,
    steps: [
      { title: 'About you', description: 'How we reach you.' },
      { title: 'Your health', description: 'What we should know before the visit.' },
    ],
    fields: [
      row(
        [field('name', { label: 'Full name', required: true })],
        [field('date', { label: 'Date of birth', required: true })]
      ),
      row(
        [field('phone', { label: 'Phone', required: true })],
        [field('email', { label: 'Email' })]
      ),
      field('address', { label: 'Address' }),
      pageBreak(),
      field('textarea', { label: 'Reason for this appointment', required: true }),
      repeater('Current medications', [
        field('text', { label: 'Medication', required: true }),
        field('text', { label: 'Dose' }),
        field('text', { label: 'How often' }),
      ]),
      field('likert', {
        label: 'How would you rate your symptoms over the past week?',
        required: true,
        options: ['No problem', 'Mild', 'Moderate', 'Severe', 'Very severe'],
      }),
      field('likert', {
        label: 'How much have symptoms affected your daily activities?',
        options: ['Not at all', 'A little', 'Somewhat', 'A lot', 'Completely'],
      }),
      field('checkbox', {
        label: 'Do any of these apply?',
        options: ['Pregnant', 'Diabetes', 'High blood pressure', 'Heart condition', 'None of these'],
      }),
      field('terms', { label: 'I consent to sharing this information with my care team', required: true }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#ecfeff',
      cardBg: '#ffffff',
      cardBorder: '#a5f3fc',
      accentColor: '#0891b2',
      labelColor: '#164e63',
      inputBg: '#f0fdff',
      inputBorder: '#a5f3fc',
      inputTextColor: '#164e63',
      textMode: 'dark',
      cardRadius: 14,
      cardShadow: 'md',
      fontFamily: 'inter',
    },
  },
];
