import type { FormTemplate } from './types';
import { field, pageBreak, row } from './types';
 
export const operationsTemplates: FormTemplate[] = [
  {
    id: 'incidentReport',
    name: 'Incident report',
    description: 'A referenced, sectioned report — what happened, when exactly, who was involved.',
    category: 'Business',
    keywords: ['incident', 'health and safety', 'accident', 'report', 'compliance', 'rica'],
    title: 'Report an incident',
    formDescription: 'File this within 24 hours. The reference is generated for you.',
    submitLabel: 'File report',
    stepIndicator: 'stepper',
    showStepHeadings: true,
    steps: [
      { title: 'The incident', description: 'What happened and exactly when.' },
      { title: 'People', description: 'Anyone involved or affected.' },
      { title: 'Follow-up', description: 'What has been done since.' },
    ],
    fields: [
      field('heading', { label: 'Reference', content: 'Incident details' }),
      field('description', {
        label: 'Intro',
        content: 'Give the facts as you observed them. Keep opinion for the follow-up section.',
      }),
      field('randomId', { label: 'Reference number' }),
      field('divider', { label: '' }),
      field('datetime', { label: 'Exactly when did it happen?', required: true }),
      field('select', {
        label: 'Type of incident',
        required: true,
        options: ['Injury', 'Near miss', 'Property damage', 'Environmental', 'Security', 'Other'],
      }),
      field('text', { label: 'Location', required: true, placeholder: 'Building, floor, area' }),
      field('textarea', {
        label: 'What happened?',
        required: true,
        placeholder: 'A factual account, in the order things occurred.',
      }),
      field('slider', { label: 'Severity, 1 to 10', required: true, min: 1, max: 10, step: 1 }),
      pageBreak(),
      field('heading', { label: 'People', content: 'Who was involved' }),
      row(
        [field('name', { label: 'Person reporting', required: true })],
        [field('email', { label: 'Your email', required: true })]
      ),
      field('multipleChoice', {
        label: 'Who was affected?',
        options: ['Staff', 'Contractor', 'Visitor', 'Member of the public', 'Nobody'],
      }),
      field('number', { label: 'How many people were involved?', min: 0, max: 200 }),
      field('yesNo', { label: 'Were the emergency services called?', required: true }),
      field('textarea', { label: 'Witness names and contact details' }),
      pageBreak(),
      field('heading', { label: 'Follow-up', content: 'Since the incident' }),
      field('textarea', { label: 'What action has already been taken?', required: true }),
      field('multipleChoice', {
        label: 'Who has been notified?',
        options: ['Line manager', 'Health and safety', 'HR', 'Insurer', 'Regulator', 'Nobody yet'],
      }),
      field('imageUpload', { label: 'Photograph of the scene' }),
      field('file', { label: 'Supporting documents' }),
      field('divider', { label: '' }),
      field('terms', {
        label: 'I confirm this account is accurate to the best of my knowledge',
        required: true,
        content:
          'A report filed here is retained for six years and may be shared with our insurer or a regulator.',
      }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#0c0a09',
      cardBg: '#ffffff',
      cardBorder: '#e7e5e4',
      accentColor: '#b91c1c',
      labelColor: '#1c1917',
      inputBg: '#fafaf9',
      inputBorder: '#d6d3d1',
      inputTextColor: '#1c1917',
      textMode: 'dark',
      cardRadius: 4,
      cardShadow: 'xl',
      fontFamily: 'inter',
      pageBackground: { gradient: 'linear-gradient(180deg, #292524 0%, #0c0a09 100%)' },
    },
  },
  {
    id: 'warrantyClaim',
    name: 'Warranty claim',
    description: 'Serial number, purchase month, and fault details, with a validated product code.',
    category: 'Commerce',
    keywords: ['warranty', 'claim', 'rma', 'return', 'repair', 'serial'],
    title: 'Make a warranty claim',
    formDescription: 'Have your product code and proof of purchase to hand.',
    submitLabel: 'Submit claim',
    stepIndicator: 'progress',
    showStepHeadings: true,
    steps: [
      { title: 'Product', description: 'What you bought and when.' },
      { title: 'The fault', description: 'What is wrong with it.' },
      { title: 'Return', description: 'Where it should go.' },
    ],
    fields: [
      field('description', {
        label: 'Intro',
        content: 'The product code is on the label underneath, in the form AB-1234.',
      }),
      field('regex', {
        label: 'Product code',
        required: true,
        pattern: '^[A-Z]{2}-\\d{4}$',
        placeholder: 'AB-1234',
        helpText: 'Two capital letters, a dash, then four digits.',
      }),
      field('text', { label: 'Serial number', required: true, unique: true }),
      row(
        [field('monthYear', { label: 'Month of purchase', required: true })],
        [field('currency', { label: 'Price paid', min: 0 })]
      ),
      field('select', {
        label: 'Where did you buy it?',
        required: true,
        options: ['Direct from us', 'Authorised reseller', 'Online marketplace', 'Gift'],
      }),
      field('file', { label: 'Proof of purchase', required: true }),
      pageBreak(),
      field('heading', { label: 'Fault', content: 'What is wrong' }),
      field('multipleChoice', {
        label: 'Which best describes the fault?',
        required: true,
        options: ['Will not power on', 'Intermittent', 'Physical damage', 'Missing parts', 'Performance'],
      }),
      field('datetime', { label: 'When did you first notice it?' }),
      field('textarea', { label: 'Describe the fault', required: true }),
      field('mediaUpload', { label: 'Photo or video of the fault' }),
      field('yesNo', { label: 'Has it been repaired before?' }),
      pageBreak(),
      field('heading', { label: 'Return', content: 'Where to collect from' }),
      row(
        [field('name', { label: 'Your name', required: true })],
        [field('phone', { label: 'Phone', required: true })]
      ),
      field('email', { label: 'Email', required: true }),
      field('address', { label: 'Collection address', required: true }),
      field('radio', {
        label: 'Preferred outcome',
        required: true,
        options: ['Repair', 'Replacement', 'Refund'],
      }),
      field('terms', { label: 'I accept the warranty terms', required: true }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#f8fafc',
      cardBg: '#ffffff',
      cardBorder: '#e2e8f0',
      accentColor: '#0369a1',
      labelColor: '#0f172a',
      inputBg: '#f8fafc',
      inputBorder: '#cbd5e1',
      inputTextColor: '#0f172a',
      textMode: 'dark',
      cardRadius: 10,
      cardShadow: 'lg',
      fontFamily: 'inter',
    },
  },
  {
    id: 'itAccessRequest',
    name: 'IT access request',
    description: 'Ticket reference, systems needed, and a dated approval window.',
    category: 'HR',
    keywords: ['it', 'access', 'permissions', 'ticket', 'systems', 'provisioning'],
    title: 'Request system access',
    formDescription: 'Approved requests are provisioned within two working days.',
    submitLabel: 'Submit request',
    fields: [
      field('heading', { label: 'Requester', content: 'Who needs access' }),
      field('uniqueId', { label: 'Ticket number' }),
      row(
        [field('name', { label: 'Full name', required: true })],
        [field('email', { label: 'Work email', required: true })]
      ),
      row(
        [field('text', { label: 'Department', required: true })],
        [field('text', { label: 'Line manager', required: true })]
      ),
      field('divider', { label: '' }),
      field('heading', { label: 'Access', content: 'What is needed' }),
      field('multipleChoice', {
        label: 'Systems',
        required: true,
        options: ['Email', 'CRM', 'Finance', 'Source control', 'Analytics', 'Admin console'],
      }),
      field('radio', {
        label: 'Level',
        required: true,
        options: ['Read only', 'Standard user', 'Administrator'],
      }),
      field('textarea', {
        label: 'Why is this access needed?',
        required: true,
        placeholder: 'Tie it to the work — "to run the monthly billing export".',
      }),
      field('spacer', { label: '' }),
      field('heading', { label: 'Duration', content: 'How long for' }),
      row(
        [field('date', { label: 'Needed from', required: true })],
        [field('date', { label: 'Needed until', helpText: 'Leave blank for permanent access.' })]
      ),
      field('yesNo', { label: 'Is this replacing someone who has left?' }),
      field('divider', { label: '' }),
      field('terms', {
        label: 'I have read the acceptable use policy',
        required: true,
        content: 'Access is logged, reviewed quarterly, and revoked automatically when you change role.',
      }),
      field('decisionBox', { label: 'Notify me when the access is live' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#0b1120',
      cardBg: '#111827',
      cardBorder: '#1f2937',
      accentColor: '#22d3ee',
      labelColor: '#e5e7eb',
      inputBg: '#0f172a',
      inputBorder: '#1f2937',
      inputTextColor: '#f9fafb',
      textMode: 'light',
      cardRadius: 10,
      cardShadow: 'lg',
      fontFamily: 'mono',
    },
  },
  {
    id: 'contractorTimesheet',
    name: 'Contractor timesheet',
    description: 'Hours to two decimals, a rate, and a signed weekly declaration.',
    category: 'HR',
    keywords: ['timesheet', 'hours', 'contractor', 'invoice', 'billing', 'week'],
    title: 'Weekly timesheet',
    formDescription: 'Submit by Monday noon for that week to make the payment run.',
    submitLabel: 'Submit timesheet',
    fields: [
      field('heading', { label: 'Period', content: 'Which week' }),
      field('uniqueId', { label: 'Timesheet number' }),
      row(
        [field('name', { label: 'Contractor', required: true })],
        [field('text', { label: 'Client or project', required: true })]
      ),
      row(
        [field('date', { label: 'Week beginning', required: true })],
        [field('monthYear', { label: 'Billing month', required: true })]
      ),
      field('divider', { label: '' }),
      field('heading', { label: 'Hours', content: 'Time worked' }),
      field('description', {
        label: 'Note',
        content: 'Record hours in decimals — an hour and a half is 1.5, not 1.30.',
      }),
      row(
        [field('decimal', { label: 'Hours worked', required: true, min: 0, max: 80 })],
        [field('decimal', { label: 'Hours on call', min: 0, max: 80 })]
      ),
      row(
        [field('currency', { label: 'Day rate', required: true, min: 0 })],
        [field('number', { label: 'Days on site', min: 0, max: 7 })]
      ),
      field('multipleChoice', {
        label: 'Which days did you work?',
        required: true,
        options: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      }),
      field('textarea', { label: 'Summary of work done', required: true }),
      field('spacer', { label: '' }),
      field('heading', { label: 'Expenses', content: 'Anything to reclaim' }),
      field('currency', { label: 'Expenses claimed', min: 0 }),
      field('file', { label: 'Receipts' }),
      field('divider', { label: '' }),
      field('terms', {
        label: 'I confirm these hours are accurate',
        required: true,
        content: 'Timesheets are checked against project records. A knowingly false claim ends the contract.',
      }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#f5f5f4',
      cardBg: '#ffffff',
      cardBorder: '#e7e5e4',
      accentColor: '#0f766e',
      labelColor: '#1c1917',
      inputBg: '#fafaf9',
      inputBorder: '#d6d3d1',
      inputTextColor: '#1c1917',
      textMode: 'dark',
      cardRadius: 6,
      cardShadow: 'md',
      fontFamily: 'mono',
    },
  },
  {
    id: 'researchScreener',
    name: 'Research screener',
    description: 'A participant screener with scales, a session slot, and a consent block.',
    category: 'Education',
    keywords: ['research', 'study', 'participant', 'screener', 'ux', 'interview'],
    title: 'Take part in our study',
    formDescription: 'Five minutes to check you are a fit. Participants receive a voucher.',
    submitLabel: 'Apply to take part',
    stepIndicator: 'dots',
    showStepHeadings: true,
    steps: [
      { title: 'About you', description: 'Basic eligibility.' },
      { title: 'Your experience', description: 'How you use tools like ours.' },
      { title: 'Scheduling', description: 'When you could join a session.' },
    ],
    fields: [
      field('description', {
        label: 'Intro',
        content: 'Answers are used only to select participants and are deleted after the study closes.',
      }),
      row(
        [field('name', { label: 'Name', required: true })],
        [field('email', { label: 'Email', required: true, unique: true })]
      ),
      field('number', { label: 'Age', required: true, min: 18, max: 120 }),
      field('text', { label: 'Where are you based?', placeholder: 'City and country' }),
      field('select', {
        label: 'Which best describes your role?',
        required: true,
        options: ['Designer', 'Engineer', 'Product', 'Research', 'Marketing', 'Something else'],
      }),
      pageBreak(),
      field('heading', { label: 'Experience', content: 'How you work today' }),
      field('slider', { label: 'How comfortable are you with new software?', required: true, min: 1, max: 10, step: 1 }),
      field('rating', { label: 'How happy are you with your current tools?', required: true, maxRating: 5 }),
      field('multipleChoice', {
        label: 'Which do you use weekly?',
        options: ['Spreadsheets', 'A form builder', 'A CRM', 'Analytics', 'None of these'],
      }),
      field('monthYear', { label: 'When did you start in this role?' }),
      field('textarea', { label: 'What is the most frustrating part of your workflow?' }),
      pageBreak(),
      field('heading', { label: 'Scheduling', content: 'Finding a slot' }),
      field('datetime', { label: 'First choice of session', required: true }),
      field('datetime', { label: 'Second choice' }),
      field('multipleChoice', {
        label: 'How would you prefer to join?',
        required: true,
        options: ['Video call', 'Phone', 'In person'],
      }),
      field('yesNo', { label: 'Are you happy for the session to be recorded?', required: true }),
      field('divider', { label: '' }),
      field('terms', {
        label: 'I consent to taking part on these terms',
        required: true,
        content:
          'Participation is voluntary and you may stop at any point. Recordings are used internally and deleted within 12 months.',
      }),
      field('decisionBox', { label: 'Tell me about future studies' }),
    ],
    theme: {
      scope: 'page',
      pageBg: '#faf5ff',
      cardBg: '#ffffff',
      cardBorder: '#e9d5ff',
      accentColor: '#7c3aed',
      labelColor: '#3b0764',
      inputBg: '#fdfaff',
      inputBorder: '#e9d5ff',
      inputTextColor: '#3b0764',
      textMode: 'dark',
      cardRadius: 16,
      cardShadow: 'lg',
      fontFamily: 'rounded',
      pageBackground: { gradient: 'linear-gradient(150deg, #ede9fe 0%, #faf5ff 60%)' },
    },
  },
];
