import type { FormTheme } from '@/types';

export interface ThemePreset {
  id: string;
  name: string;
  /** Applied over the form's current theme, keeping its scope. */
  theme: Omit<FormTheme, 'scope'>;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'classic',
    name: 'Classic',
    theme: {
      pageBg: '#f1f3f5',
      cardBg: '#ffffff',
      cardBorder: '#e9ecef',
      accentColor: '#4c6ef5',
      labelColor: '#212529',
      inputBg: '#ffffff',
      inputBorder: '#ced4da',
      inputTextColor: '#212529',
      textMode: 'dark',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    theme: {
      pageBg: '#0b0c0f',
      cardBg: '#15171c',
      cardBorder: '#25272e',
      accentColor: '#5c7cfa',
      labelColor: '#e9ecef',
      inputBg: '#1c1e25',
      inputBorder: '#2f323b',
      inputTextColor: '#f1f3f5',
      textMode: 'light',
    },
  },
  {
    id: 'sky',
    name: 'Sky',
    theme: {
      pageBg: '#dbeafe',
      cardBg: '#ffffff',
      cardBorder: '#bfdbfe',
      accentColor: '#2563eb',
      labelColor: '#1e293b',
      inputBg: '#f8fafc',
      inputBorder: '#cbd5e1',
      inputTextColor: '#0f172a',
      textMode: 'dark',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    theme: {
      pageBg: '#052e23',
      cardBg: '#0b4034',
      cardBorder: '#125a48',
      accentColor: '#10b981',
      labelColor: '#d1fae5',
      inputBg: '#0f4c3d',
      inputBorder: '#166b55',
      inputTextColor: '#ecfdf5',
      textMode: 'light',
    },
  },
  {
    id: 'blush',
    name: 'Blush',
    theme: {
      pageBg: '#fce7f3',
      cardBg: '#ffffff',
      cardBorder: '#f9cee5',
      accentColor: '#db2777',
      labelColor: '#500724',
      inputBg: '#fffafc',
      inputBorder: '#f5cddf',
      inputTextColor: '#3f0f26',
      textMode: 'dark',
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    theme: {
      pageBg: '#fef3c7',
      cardBg: '#ffffff',
      cardBorder: '#fde68a',
      accentColor: '#d97706',
      labelColor: '#451a03',
      inputBg: '#fffbeb',
      inputBorder: '#fcd34d',
      inputTextColor: '#451a03',
      textMode: 'dark',
    },
  },
  {
    id: 'grape',
    name: 'Grape',
    theme: {
      pageBg: '#ede9fe',
      cardBg: '#ffffff',
      cardBorder: '#ddd6fe',
      accentColor: '#7c3aed',
      labelColor: '#2e1065',
      inputBg: '#faf8ff',
      inputBorder: '#d8ccff',
      inputTextColor: '#2e1065',
      textMode: 'dark',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    theme: {
      pageBg: '#1e293b',
      cardBg: '#293548',
      cardBorder: '#3a4759',
      accentColor: '#38bdf8',
      labelColor: '#e2e8f0',
      inputBg: '#334155',
      inputBorder: '#475569',
      inputTextColor: '#f1f5f9',
      textMode: 'light',
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    theme: {
      pageBg: '#fafafa',
      cardBg: '#ffffff',
      cardBorder: '#e5e5e5',
      accentColor: '#171717',
      labelColor: '#171717',
      inputBg: '#fafafa',
      inputBorder: '#d4d4d4',
      inputTextColor: '#171717',
      textMode: 'dark',
    },
  },
  {
    id: 'teal',
    name: 'Teal',
    theme: {
      pageBg: '#ccfbf1',
      cardBg: '#ffffff',
      cardBorder: '#99f6e4',
      accentColor: '#0d9488',
      labelColor: '#134e4a',
      inputBg: '#f0fdfa',
      inputBorder: '#99f6e4',
      inputTextColor: '#134e4a',
      textMode: 'dark',
    },
  },
  {
    id: 'coffee',
    name: 'Coffee',
    theme: {
      pageBg: '#2b1d16',
      cardBg: '#3b2a20',
      cardBorder: '#543d2f',
      accentColor: '#d9a066',
      labelColor: '#f3e6da',
      inputBg: '#473327',
      inputBorder: '#63483a',
      inputTextColor: '#f8f1ea',
      textMode: 'light',
    },
  },
  {
    id: 'ink',
    name: 'Ink',
    theme: {
      pageBg: '#111827',
      cardBg: '#ffffff',
      cardBorder: '#ffffff',
      accentColor: '#111827',
      labelColor: '#111827',
      inputBg: '#f9fafb',
      inputBorder: '#d1d5db',
      inputTextColor: '#111827',
      textMode: 'dark',
    },
  },
  {
    id: 'crimson',
    name: 'Crimson',
    theme: {
      pageBg: '#fee2e2',
      cardBg: '#ffffff',
      cardBorder: '#fecaca',
      accentColor: '#dc2626',
      labelColor: '#450a0a',
      inputBg: '#fffafa',
      inputBorder: '#fecaca',
      inputTextColor: '#450a0a',
      textMode: 'dark',
    },
  },
  {
    id: 'lagoon',
    name: 'Lagoon',
    theme: {
      pageBg: '#082f49',
      cardBg: '#0c4a6e',
      cardBorder: '#155e83',
      accentColor: '#22d3ee',
      labelColor: '#e0f2fe',
      inputBg: '#0e5a83',
      inputBorder: '#1a6f9c',
      inputTextColor: '#f0f9ff',
      textMode: 'light',
    },
  },
  {
    id: 'sand',
    name: 'Sand',
    theme: {
      pageBg: '#efe7db',
      cardBg: '#fdfaf5',
      cardBorder: '#e0d5c3',
      accentColor: '#a16207',
      labelColor: '#3f2d13',
      inputBg: '#ffffff',
      inputBorder: '#ded2be',
      inputTextColor: '#3f2d13',
      textMode: 'dark',
    },
  },
  {
    id: 'plum',
    name: 'Plum',
    theme: {
      pageBg: '#2e1065',
      cardBg: '#3b1d7a',
      cardBorder: '#4c2a95',
      accentColor: '#c084fc',
      labelColor: '#ede9fe',
      inputBg: '#452490',
      inputBorder: '#5b34ad',
      inputTextColor: '#f5f3ff',
      textMode: 'light',
    },
  },
  {
    id: 'mint',
    name: 'Mint',
    theme: {
      pageBg: '#dcfce7',
      cardBg: '#ffffff',
      cardBorder: '#bbf7d0',
      accentColor: '#16a34a',
      labelColor: '#14532d',
      inputBg: '#f7fef9',
      inputBorder: '#bbf7d0',
      inputTextColor: '#14532d',
      textMode: 'dark',
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    theme: {
      pageBg: '#1c1c1e',
      cardBg: '#2c2c2e',
      cardBorder: '#3a3a3c',
      accentColor: '#0a84ff',
      labelColor: '#f2f2f7',
      inputBg: '#3a3a3c',
      inputBorder: '#48484a',
      inputTextColor: '#ffffff',
      textMode: 'light',
    },
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    theme: {
      pageBg: '#f3d9d3',
      cardBg: '#ffffff',
      cardBorder: '#e8c4bb',
      accentColor: '#b76e79',
      labelColor: '#4a2c2a',
      inputBg: '#fffbfa',
      inputBorder: '#e8c4bb',
      inputTextColor: '#4a2c2a',
      textMode: 'dark',
    },
  },
  {
    id: 'lime',
    name: 'Lime',
    theme: {
      pageBg: '#1a2e05',
      cardBg: '#233d08',
      cardBorder: '#365314',
      accentColor: '#a3e635',
      labelColor: '#ecfccb',
      inputBg: '#2b4a0c',
      inputBorder: '#3f6212',
      inputTextColor: '#f7fee7',
      textMode: 'light',
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    theme: {
      pageBg: '#ffffff',
      cardBg: '#ffffff',
      cardBorder: '#e5e7eb',
      accentColor: '#2563eb',
      labelColor: '#111827',
      inputBg: '#ffffff',
      inputBorder: '#d1d5db',
      inputTextColor: '#111827',
      textMode: 'dark',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    theme: {
      pageBg: '#fb923c',
      cardBg: '#ffffff',
      cardBorder: '#fed7aa',
      accentColor: '#ea580c',
      labelColor: '#431407',
      inputBg: '#fffbf7',
      inputBorder: '#fed7aa',
      inputTextColor: '#431407',
      textMode: 'dark',
    },
  },
  {
    id: 'steel',
    name: 'Steel',
    theme: {
      pageBg: '#e2e8f0',
      cardBg: '#ffffff',
      cardBorder: '#cbd5e1',
      accentColor: '#475569',
      labelColor: '#0f172a',
      inputBg: '#f8fafc',
      inputBorder: '#cbd5e1',
      inputTextColor: '#0f172a',
      textMode: 'dark',
    },
  },
];
